import React, { useMemo } from 'react'
import { geoMercator, geoPath } from 'd3-geo'
import worldGeoJSON from '../../../data/worldMap.json'

const MAP_WIDTH = 1000
const MAP_HEIGHT = 450

// Real-world geo-coordinates: [Longitude, Latitude]
const locationCoords = [
  // North America
  [-122.4194, 37.7749], // San Francisco
  [-74.0060, 40.7128],  // New York
  [-87.6298, 41.8781],  // Chicago
  [-99.1332, 19.4326],  // Mexico City
  // Europe
  [-0.1276, 51.5074],   // London
  [13.4050, 52.5200],   // Berlin
  [12.4964, 41.9028],   // Rome
  // Asia
  [77.2090, 28.6139],   // New Delhi
  [121.4737, 31.2304],  // Shanghai
  [139.6917, 35.6895],  // Tokyo
  [103.8198, 1.3521],   // Singapore
  // Australia
  [151.2093, -33.8688], // Sydney
  // South America
  [-46.6333, -23.5505], // Sao Paulo
  [-77.0428, -12.0464], // Lima
  // Africa
  [3.3792, 6.5244],     // Lagos
  [28.0473, -26.2041],  // Johannesburg
]

const PulseDot = ({ left, top }) => (
  <div className="absolute w-[10px] h-[10px] -translate-x-1/2 -translate-y-1/2" style={{ left, top }}>
    <div className="relative w-2 h-2 rounded-full bg-orange-600 animate-pulseDot shadow-[0_0_6px_rgba(234,88,12,0.6)]">
      <div className="absolute inset-[-4px] rounded-full bg-orange-600/30 animate-pulseRing"></div>
    </div>
  </div>
)

export default function GlobeSection() {
  const { paths, projectedDots } = useMemo(() => {
    // Create base projection
    const baseProjection = geoMercator()
      .fitSize([MAP_WIDTH, MAP_HEIGHT], worldGeoJSON)

    // Increase scale significantly (1.5x) to make the map wider and more visible in the box.
    // Shift it slightly down (y + 40) to center populated landmasses (North America/Europe) 
    // while letting Antarctica naturally overflow the bottom box limit.
    const currentScale = baseProjection.scale()
    const currentTranslate = baseProjection.translate()
    
    const projection = baseProjection
      .scale(currentScale * 1.5)
      .translate([currentTranslate[0], currentTranslate[1] + 40])

    const pathGenerator = geoPath().projection(projection)

    const paths = worldGeoJSON.features.map((feature, i) => (
      <path
        key={i}
        d={pathGenerator(feature)}
        fill="currentColor"
      />
    ))

    const projectedDots = locationCoords.map((coord, index) => {
      const [x, y] = projection(coord)
      return <PulseDot key={index} left={`${(x / MAP_WIDTH) * 100}%`} top={`${(y / MAP_HEIGHT) * 100}%`} />
    })

    return { paths, projectedDots }
  }, [])

  return (
    <section className="py-24 bg-white dark:bg-[#0a0f1a] relative overflow-hidden transition-colors duration-300">
      <div className="max-w-[1280px] mx-auto px-4 sm:px-6">
        
        {/* Dark Card Container */}
        <div className="bg-[#0b0f19] dark:bg-slate-900/40 rounded-[32px] md:rounded-[40px] shadow-2xl border border-transparent dark:border-slate-800/60 overflow-hidden relative pt-[72px] pb-[60px] px-6 md:px-12">
          
          {/* Subtle Orange Glow behind text */}
          <div className="absolute top-[30%] left-1/2 -translate-x-1/2 w-[700px] h-[500px] bg-orange-600/15 blur-[120px] rounded-[100%] pointer-events-none"></div>

          <div className="text-center relative z-20 mb-12">
            <div className="inline-block border border-orange-500/30 bg-orange-500/10 rounded-full px-3 py-1 text-[11px] font-bold tracking-widest uppercase text-orange-500 mb-6 tracking-[0.12em]">
              GLOBAL REACH
            </div>
            <h2 className="text-[clamp(44px,6vw,80px)] font-light tracking-[-2px] leading-[1.05] text-white">
              Supporting clients<br/>around the globe
            </h2>
          </div>

          <div className="relative max-w-[1000px] mx-auto h-[350px] sm:h-[450px] mb-8 rounded-[20px] overflow-hidden">
            {/* SVG Base map generated by D3 */}
            <svg 
              viewBox={`0 0 ${MAP_WIDTH} ${MAP_HEIGHT}`} 
              className="absolute inset-0 w-full h-full text-slate-800/70"
            >
              {paths}
            </svg>

            {/* Overlays / Glows */}
            <div className="absolute inset-0 pointer-events-none mix-blend-screen" style={{ background: 'radial-gradient(ellipse 60% 40% at 50% 50%, rgba(234,88,12,0.12) 0%, transparent 70%), radial-gradient(ellipse 80% 60% at 50% 80%, rgba(59,130,246,0.08) 0%, transparent 70%)' }}></div>

            {/* Grid lines overlay */}
            <div className="absolute inset-0 overflow-hidden mix-blend-overlay">
              <svg className="w-full h-full opacity-10" viewBox={`0 0 ${MAP_WIDTH} ${MAP_HEIGHT}`} preserveAspectRatio="none">
                <path d={`M0,${MAP_HEIGHT * 0.5} Q${MAP_WIDTH/4},${MAP_HEIGHT * 0.4} ${MAP_WIDTH/2},${MAP_HEIGHT * 0.5} T${MAP_WIDTH},${MAP_HEIGHT * 0.5}`} fill="none" stroke="white" strokeWidth="0.5"/>
                <path d={`M0,${MAP_HEIGHT * 0.3} Q${MAP_WIDTH/4},${MAP_HEIGHT * 0.25} ${MAP_WIDTH/2},${MAP_HEIGHT * 0.3} T${MAP_WIDTH},${MAP_HEIGHT * 0.3}`} fill="none" stroke="white" strokeWidth="0.5"/>
                {[100, 200, 300, 400, 500, 600, 700, 800, 900].map((x) => (
                  <line key={x} x1={x} y1={0} x2={x} y2={MAP_HEIGHT} stroke="white" strokeWidth="0.3" strokeOpacity="0.2" strokeDasharray="4,12"/>
                ))}
              </svg>
            </div>
            
            {/* Math projected pulse dots */}
            <div className="absolute inset-0">
               {projectedDots}
            </div>
          </div>

          {/* Stats Box */}
          <div className="max-w-[900px] mx-auto grid grid-cols-1 sm:grid-cols-2 gap-8 bg-white/[0.03] border border-white/[0.05] rounded-[24px] p-8 md:p-10 relative z-20 backdrop-blur-sm">
            
            {/* Stat 1 */}
            <div>
              <div className="flex items-center gap-2 mb-3">
                <div className="flex items-center justify-center w-[22px] h-[22px] rounded-full bg-blue-600 shadow-[0_0_12px_rgba(37,99,235,0.6)]">
                  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" className="text-white">
                    <path d="M12 2L14.4 8.5L21.2 9L15.9 13.4L17.6 20L12 16.5L6.4 20L8.1 13.4L2.8 9L9.6 8.5L12 2Z" fill="currentColor"/>
                  </svg>
                </div>
                <span className="text-orange-500 font-bold text-[17px]">Global IT Support</span>
              </div>
              <p className="text-[13px] text-gray-400 leading-[1.6]">
                Get dedicated 24/7 IT support and remote administration for your business, no matter where you are located. We serve clients across the globe.
              </p>
            </div>

            {/* Stat 2 */}
            <div>
              <div className="flex items-center gap-2 mb-3">
                <div className="flex items-center justify-center w-[22px] h-[22px]">
                  <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor" className="text-orange-500 drop-shadow-[0_0_8px_rgba(249,115,22,0.8)]">
                    <path d="M12 4L22 20H2L12 4Z" />
                  </svg>
                </div>
                <span className="text-orange-500 font-bold text-[17px]">Worldwide ERP Deployment</span>
              </div>
              <p className="text-[13px] text-gray-400 leading-[1.6]">
                Deploy the powerful LedgerCart ERP architecture securely and reliably, backed by our global network of infrastructure partners.
              </p>
            </div>

          </div>
        </div>
      </div>
    </section>
  )
}
